name: ci-pipeline

on:
 push:
  branches:
    - main*

  paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'

jobs:
  build-and-test:
    runs-on: self-hosted
    env:
      SOLUTIONPATH: src/Poke.API.Facade.sln
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dot net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Build code
        run: dotnet build ${{env.SOLUTIONPATH}}
      
      - name: Make Directory for test results
        run: mkdir -p testresults

      
      - name: Run Xunit Tests
        run: dotnet test ${{env.SOLUTIONPATH}} --logger html --results-directory testresults --no-build
      
      
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name : TestRunReports
          path: testresults
          #

