name: ci-pipeline
on:
 push:
  branches:
    - main*

  paths-ignore:
    - '**/*.md'
    - '**/*.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '3.1.x'
      SOLUTIONPATH: 'src/Poke.API.Facade.sln'

    steps: 

     #Setup dotnet
     - name: Setup DotNet ${{ env.DOTNET_VERSION }}
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

      #Build code
     - name: Build code
       uses: dotnet build --configuration Release ${{ env.SOLUTIONPATH }}  --output ./output

      
      #Make Dir
     - name: make directory for test
       run: mkdir -p testdir

      #Run unit test
     - name: Run unit test
       run: dotnet test  ${{ env.SOLUTIONPATH }} --logger html --results-directory testdir --no-build

      #upload artifacts
     - name: Upload test results
       uses: actions/upload-artifact@v2
       with:
        name: Upload artifacts
        path: testdir     
